function handle = guiAnalysisPanel(parentHandle,position)
% GUIANALYSISPANEL Add a panel displaying some analysis controls to a gui
%       Should only be called from within a GUI defining function.
%
%       Arguments: parent Handle and position vector.
%
%       Returns the handle of the added panel.

% Copyright (c) 2011-14, Till Biskup
% 2014-08-12

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Construct the components
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

defaultBackground = get(parentHandle,'Color');

handle = uipanel('Tag','analysis_panel',...
    'parent',parentHandle,...
    'Title','Data analysis',...
    'FontUnit','Pixel','Fontsize',12,...
    'FontWeight','bold',...
    'BackgroundColor',defaultBackground,...
    'Visible','off',...
    'Units','pixels','Position',position);

% Create the "Help" panel
handle_size = get(handle,'Position');
uicontrol('Tag','analysis_panel_description',...
    'Style','text',...
    'Parent',handle,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'HorizontalAlignment','Left',...
    'FontAngle','oblique',...
    'Position',[10 handle_size(4)-60 handle_size(3)-20 30],...
    'String',{'Analysis tools such as data fitting, deconvolution (SVD), ...'}...
    );

handle_p1 = uipanel('Tag','analysis_panel_dataexport_panel',...
    'Parent',handle,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[10 handle_size(4)-170 handle_size(3)-20 100],...
    'Title','Export data'...
    );
uicontrol('Tag','analysis_panel_dataexport_description',...
    'Style','text',...
    'Parent',handle_p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'HorizontalAlignment','Left',...
    'FontAngle','oblique',...
    'Position',[10 35 handle_size(3)-40 40],...
    'String',{'Export currently active dataset for external analysis.'}...
    );
uicontrol('Tag','analysis_panel_dataexport_format_text',...
    'Style','text',...
    'Parent',handle_p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'HorizontalAlignment','left',...
    'Units','Pixels',...
    'Position',[10 10 60 20],...
    'String','Format'...
    );
uicontrol('Tag','analysis_panel_dataexport_format_popupmenu',...
    'Style','popupmenu',...
    'Parent',handle_p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[handle_size(3)-190 15 100 20],...
    'String','glotaran|ASCII (2D)',...
    'TooltipString','Select format of export'...
    );
uicontrol('Tag','analysis_panel_dataexport_pushbutton',...
    'Style','pushbutton',...
    'Parent',handle_p1,...
    'BackgroundColor',defaultBackground,...
    'FontUnit','Pixel','Fontsize',12,...
    'Units','Pixels',...
    'Position',[handle_size(3)-90 10 60 30],...
    'String','Export',...
    'TooltipString','Export current axis to graphics file with given format',...
    'Callback',{@pushbutton_Callback,'Export'}...
    );


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Initialization tasks
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Callbacks
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function pushbutton_Callback(~,~,action)
    try
        if isempty(action)
            return;
        end
        
        % Get appdata of main window
        mainWindow = TAguiGetWindowHandle();
        ad = getappdata(mainWindow);
        
        % Get handles of main window
        gh = guihandles(mainWindow);

        active = ad.control.spectra.active;
        
        switch lower(action)
            case 'export'
                if ~active
                    return;
                end

                % Get export format
                exportFormats = cellstr(...
                    get(gh.analysis_panel_dataexport_format_popupmenu,'String'));
                exportFormat = exportFormats{...
                    get(gh.analysis_panel_dataexport_format_popupmenu,'Value')};
                                
                switch exportFormat
                    case 'glotaran'
                        fileExtension = 'ascii';
                        exportFunctionName = 'export4glotaran';
                    case 'ASCII (2D)'
                        fileExtension = 'ascii';
                        exportFunctionName = 'TAexport2D';
                    otherwise
                        fprintf('%s%s "%s"\n',...
                            'TAgui : guiAnalysisPanel() : ',...
                            'pushbutton_Callback(): Unknown export format',...
                            exportFormat);
                        return;
                end
                
                % Generate default file name
                [~,fileNameSuggested,~] = ...
                    fileparts(ad.data{active}.file.name);
                % Ask user for file name
                [fileName,pathName] = uiputfile(...
                    sprintf('*.%s',fileExtension),...
                    'Get filename to export figure to',...
                    fileNameSuggested);
                % If user aborts process, return
                if fileName == 0
                    return;
                end
                % Create filename with full path
                fileName = fullfile(pathName,fileName);
                
                TAbusyWindow('start',...
                    'Trying to export dataset...<br />please wait.');
                
                exportFunction = str2func(exportFunctionName);
                
                % Export using export4glotaran
                status = exportFunction(...
                    ad.data{ad.control.spectra.active},fileName);
                if status
                    TAmsg(status,'error');
                    TAbusyWindow('stop',...
                        'Trying to export dataset...<br /><b>failed</b>.');
                else
                    TAbusyWindow('stop',...
                        'Trying to export dataset...<br /><b>done</b>.');
                    TAbusyWindow('deletedelayed');
                end
                
                % Add status message (mainly for debug reasons)
                % IMPORTANT: Has to go AFTER setappdata
                msgStr = sprintf('Exported dataset %i to format %s',...
                    ad.control.spectra.active,exportFormat);
                TAmsg(msgStr,'info');
            otherwise
                fprintf('%s%s "%s"\n',...
                    'TAgui : guiAnalysisPanel() : ',...
                    'pushbutton_Callback(): Unknown action',...
                    action);
                return;
        end
    catch exception
        TAexceptionHandling(exception);
    end
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Utility functions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

end
